# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Retrotxt < Formula
  desc "RetroTxtGo is the tool that turns ANSI, ASCII, NFO text into in-browser HTML."
  homepage "https://retrotxt.com/go"
  version "0.0.37"
  license "LGPL 3.0"
  depends_on :macos

  on_macos do
    url "https://github.com/bengarrett/homebrew-retrotxt/releases/download/v0.0.37/homebrew-retrotxt_darwin_all.tar.gz"
    sha256 "fed625821b71dda453d4a2c773c5c9cab6da9261be43b51309f20c80ff199fab"

    def install
      bin.install "retrotxt"
    end
  end

  test do
    system "#{bin}/retrotxt --version"
  end
end
